name: CI/CD - Build & Test Java with SMTP4DEV

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupération du code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Démarrer smtp4dev dans Docker
      - name: Start smtp4dev container
        run: |
          docker run -d --name smtp4dev \
            -p 5000:80 -p 25:25 -p 143:143 \
            rnwood/smtp4dev:v3
          sleep 5 # Attendre que le serveur démarre

      # 3️⃣ Vérifier que smtp4dev tourne bien
      - name: Check running containers
        run: docker ps

      # 4️⃣ Vérifier l'accès à l'interface Web de smtp4dev
      - name: Test smtp4dev Web UI
        run: curl --fail http://localhost:5000 || exit 1

      # 5️⃣ Vérifier que le serveur SMTP écoute bien
      - name: Test SMTP connection
        run: nc -zv localhost 25 || exit 1

      # 6️⃣ Configurer JDK 21 et Maven
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      # 7️⃣ Construire et tester le projet Maven
      - name: Build and test with Maven
        run: mvn clean verify
